const products =[
    {   
        category : `apparel`,
        name : `Nike Sportwear`,
        brand : `Nike`,
        size : ['S','M','L','XL','XXL'],
        color : ['white','black','grey'],
        gender : ['male','female'],
                 
        price : 48,
        productType : `T- Shirt`,
           
    },
    {   
        category : `apparel`,
        name : `Nike Dri-FIT Player`,
        brand : `Nike`,
        size : ['S','M','L','XL','XXL'],
        color : ['white','black','grey',],
        gender : ['male'],
        price : 150,
        productType : `Polo`,
    },
    {   
        category : `apparel`,
        name : `Short-Sleeve Running Top`,
        brand : `Nike`,
        size : ['S','M','L','XL'],
        color : ['white','black','grey'],
        gender : ['famale'],
        price : 220,
        productType : `T-shirt`,
    },
    {   
        category : `shoes`,
        name : `Nike Air Force 1 Crater`,
        brand : `Nike`,
        size : [7,7.5,8,8.5,9,9.5,10,10.5,11,11.5,12],
        color : ['black','pink','blue','white'],
        gender : ['male','female'],
        price : 1050,
        productType : `originals`,
    },
    {   
        category : `shoes`,
        name : `Nike Air Force 1 React LV8`,
        brand : `Nike`,
        size : [7,7.5,8,8.5,9,9.5,10,10.5,11,11.5,12],
        color : ['cyan','yellow','black','white'],
        gender : ['male','female'],
        price : 900,
        productType : `originals`,
    },
    {   
        category : `shoes`,
        name : `Nike Tạnun`,
        brand : `Nike`,
        size : [7,7.5,8,8.5,9,9.5,10,10.5,11,11.5,12],
        color : ['cyan','yellow','black','white'],
        gender : ['male'],
        price : 1500,
        productType : `running`,
    },
    {   
        category : `apparel`,
        name : `Nike BETRUE`,
        brand : `Nike`,
        size : ['S','M','L','XL','XXL'],
        color : ['white','black'],
        gender : ['male'],
        price : 780,
        productType : `hoodie`,
    },
    {   
        category : `apparel`,
        name : `Nike Sport Tech Pack`,
        brand : `Nike`,
        size : ['S','M','L','XL','XXL'],
        color : ['white','black','blue'],
        gender : ['male','female'],
        price : 468,
        productType : `Jacket`,
    },
    {   
        category : `apparel`,
        name : `Nike SportSwear`,
        brand : `Nike`,
        size : ['S','M','L','XL'],
        color : ['Track Rede'],
        gender : ['female'],
        price : 860,
        productType : `Dress`,
    },
    {   
        category : `apparel`,
        name : `Nike Essential`,
        brand : `Nike`,
        size : ['S','M','L','XL','XXL'],
        color : ['white','black','grey'],
        gender : ['male'],
        price : 400,
        productType : `pants `,
    }, 
]

